language: node_js
node_js:
  - 14
branches:
  only:
    - master
before_script:
  - yarn install
  - cd projects/stlmpp/store
  - yarn install
  - cd ../utils
  - yarn install
  - cd ../router
  - yarn install
  - cd ../control
  - yarn install
script:
  - cd ../../../
  - yarn coverage-store
  - yarn coverage-utils
  - yarn coverage-router
  - yarn coverage-control
  - yarn combine-coverage
after_success: 'yarn coveralls'
